Add assertions to detect FD_SET overflow
QubesOS/qubes-core-qubesdb pull request #39
Opened 2021-10-20 18:04 UTC by DemiMarie

This is undefined behavior, so crashing is better.

2021-10-30 01:01 UTC, marmarek requested changes

2021-10-30 01:01 UTC, marmarek commented on daemon/qubesdb_internal.h
> +#undef NDEBUG
Same as in the other PR.

2022-01-05 16:19 UTC, marmarek commented
PipelineRetry

2022-01-05 18:03 UTC, marmarek commented
This fails to build on all the targets (see CI).

2022-01-05 18:56 UTC, DemiMarie commented
Fixed

2022-02-05 17:05 UTC, marmarek approved these changes

2022-02-05 17:19 UTC, merged