QWT-cross sync
QubesOS/qubes-core-qubesdb pull request #45
Opened 2021-12-29 15:34 UTC by jevank

Apply stalled MinGW and qubes-windows-tools-cross patches. See commit messages to details

2022-01-05 18:21 UTC, marmarek requested changes

2022-01-05 18:21 UTC, marmarek commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
This is a footgun - if client struct would have any mutable state, it would easily desynchronize. Right now _on Windows_ it doesn't have any, but on Linux it does (`next` pointer, at the very least). I think right now incidentally it would work, but generally, I don't like it.

I guess you hit a case when client disconnects while some of its watch is still registered, right? `handle_client_disconnect()` in `db-cmds.c` should take care of this case - maybe there is some Windows-specific issue with that?

2022-01-05 18:54 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
I had doubt about these changes, thanks.

As I remember it was floating use-after-free issue with qubesdb-daemon crushed. I'm afraid @mlukashov  won't be able to answer these days, I'll try to see for myself.

2022-01-05 19:39 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
It might be the reason - pipe thread with client struct in stack might finished too fast and watcher broke qubesdb... But I'm not sure.
https://github.com/QubesOS/qubes-core-qubesdb/blob/4f9dfb335b526ecd48357e09612fb5db230ead00/daemon/db-daemon.c#L249-L275

2022-01-06 03:56 UTC, marmarek commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
Hmm, it may be something here indeed - `QpsDisconnectClient` does not call `handle_client_disconnect()`, so the watches are not cleaned up in this case. Can you try adding `handle_client_disconnect(p->daemon, &c)` call just before `QpsDisconnectClient` in both those cases?

BTW, since this use threads, it could use some locking on access calls to `handle_*`, currently it has great potential for corrupting the db structures...

2022-01-06 08:33 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
You are right - disconnected client could be easily reproduced and it crushes the daemon. I will check your proposition today with some stress tests, because we saw intermittent crushes w/o disconnecting.

2022-01-06 12:10 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
>Can you try adding handle_client_disconnect(p->daemon, &c) call just before QpsDisconnectClient in both those cases?

This solves disconnected client, but still possible to crushes (I suppose racing between closing and notifying).
https://gist.github.com/jevank/34a0d80612178846e67088ac5fed145e

What about ifdef WIN32 while storing client id on watcher create?

2022-01-06 12:20 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
> BTW, since this uses threads, it could use some locking on handle_* calls, currently it has great potential for corrupting the db structures...

Agree

2022-01-06 12:39 UTC, marmarek commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
> What about ifdef WIN32 while storing client id on watcher create?

Watch code (especially on cleanup) compares `client` _pointers_, so if you allocate new one for each watch, it wouldn't match.

Try those two commits: https://github.com/QubesOS/qubes-core-qubesdb/pull/46

2022-01-06 12:46 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
> Watch code (especially on cleanup) compares client pointers, so if you allocate new one for each watch, it wouldn't match.

Ok. I will try, thanks

2022-01-06 13:38 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
Builds and works fine with stress tests too.

2022-01-06 13:44 UTC, marmarek commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
Can you adjust your commits to not conflict with the other PR (basically drop copying client, and adding handle_client_disconnect)? Or cherry-pick mine commits into this PR, whatever you prefer.

2022-01-06 14:07 UTC, jevank commented on daemon/db-core.c
> +    memcpy(new_watch->client, client, sizeof(*client));
I've cherry-picked for build and pushed here too.

2022-01-20 02:07 UTC, marmarek approved these changes

2022-02-05 17:19 UTC, merged