Make systemd configurable
QubesOS/qubes-core-qubesdb pull request #8
Opened 2017-12-25 21:20 UTC by newchain

I have been using this since @marmarek gave it to me, with a couple of line changes for 3.2.

2017-12-25 22:55 UTC, marmarek requested changes
The code itself is ok, but the missing part is setting HAVE_SYSTEMD anywhere. Can be CFLAGS in daemon/Makefile, for example:
```
ifneq (0,$(USE_SYSTEMD))
CFLAGS += -DHAVE_SYSTEMD
endif
```
(put systemd-related cflags and libs there too).
Then, you can build without systemd by `make USE_SYSTEMD=0`

2017-12-26 10:59 UTC, newchain commented
> The code itself is ok, but the missing part is setting HAVE_SYSTEMD anywhere. Can be CFLAGS in daemon/Makefile, for example:

Sorry - you included that part but the hunk got lost while applying.

2018-01-04 01:26 UTC, newchain commented
> The code itself is ok, but the missing part is setting HAVE_SYSTEMD anywhere. Can be CFLAGS in daemon/Makefile, for example:

Clarification @marmarek : the updated commit has the Makefile part.

2018-01-05 18:11 UTC, marmarek requested changes

2018-01-05 18:11 UTC, marmarek commented on daemon/Makefile
> +CFLAGS += `pkg-config --cflags libsystemd || pkg-config --cflags libsystemd-daemon`
`-DHAVE_SYSTEMD` is needed here, in addition to systemd libraries.

2019-09-17 02:29 UTC, closed without merging